### ISSUE TITLE
Micronaut with Spring support

### ISSUE THREAD

**Issue by bnusunny** [bnusunny/supersonic-java-on-lambda#3]
create samples for micronaut with spring support

**Comment by FaisalShabbir007** [comment]
@RestController
public class MyAppController {

    @GetMapping("/hello")
    public String hello() {
        return "Hello from MyAppController!";
    }
}


@SpringComponentScan
public class Application {

    public static void main(String[] args) {
        Micronaut.run(Application.class);
    }
}

@Service
public class GreetingService {

    public String greet() {
        return "Hello from Spring Service!";
    }
}

@SpringComponent("greetingService")
public class Application {

    public static void main(String[] args) {
        Micronaut.run(Application.class);
    }
}

@Configuration
public class MyConfiguration {

    @Bean
    public MyBean myBean() {
        return new MyBean();
    }
}

// Bean class
public class MyBean {

    public String getData() {
        return "Data from Spring Bean!";
    }
}

@SpringBean("myBean")
public class Application {

    public static void main(String[] args) {
        Micronaut.run(Application.class);
    }
}

**Comment by bnusunny** [comment]
Thank you! This is an old repo. GraalVM and Micronaut have grown a lot. It's better to look at their documents. 

I will achieve this repo.
