### ISSUE TITLE
quarkus-dynamodb not working

### ISSUE THREAD

**Issue by drissamri** [bnusunny/supersonic-java-on-lambda#5]
I tried to give your example a go, but I get the following exception at runtime - the graalvm layer is deployed and used: 

`WARNING: The sunec native library, required by the SunEC provider, could not be loaded. This library is usually shipped as part of the JDK and can be found under <JAVA_HOME>/jre/lib/<platform>/libsunec.so. It is loaded at run time via System.loadLibrary("sunec"), the first time services from SunEC are accessed. To use this provider's services the java.library.path system property needs to be set accordingly to point to a location that contains libsunec.so. Note that if java.library.path is not set it defaults to the current working directory.`

**Comment by bnusunny** [comment]
Do you deploy the lambda with the deploy.sh script? In that [script](https://github.com/bnusunny/supersonic-java-on-lambda/blob/95e9e5d9a2979e3f9a5571cf8e518d3848f17321/quarkus-on-lambda-dynamodb/deploy.sh#L12), I use system properties to pass the locations to native image.  

You can also solve this by copy libsunec.so and cacerts to the same location as native image in the custom runtime.

**Comment by bnusunny** [comment]
@drissamri Did you get the example working? Please let me know if you need any additional information.

**Comment by bnusunny** [comment]
@drissamri I see in [this commit](https://github.com/drissamri/multi-region-lambda/tree/a41b5fec0ac6eb02d195ef692108b944032924c6) you already get the Dynamodb working. I'll close this issue now. Please feel free to reopen if you still have problems.
